{{- $service := include "service.resolved" (dict "root" $ "service_name" "queue-worker") | fromYaml -}}
{{ template "service.environment.secret" (dict "service_name" "queue-worker" "service" $service "root" $) }}
